baseURL = "https://hugo-theme-massively.netlify.com/"
languageCode = "en-us"
title = "Deep Space Loneliness"
subtitle = "A Saga through space, time & emotions "
theme = "massively"
paginate = 5

googleanalytics = ""

[params]
  # set below parameter to define a favicon
  favicon = "favicon.ico"
  # set to change date format
  dateFormat = "2.1.2006"


[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Massively - Versión Español"
